services:
    admin.blog.article:
        class: modius22\BlogBundle\Admin\BlogAdmin
        arguments: [~, modius22\BlogBundle\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, translation_domain: messages, group: label.admin.group.blog_bundle, label: label.blog.admin.article, label_translator_strategy: sonata.admin.label.strategy.underscore  }
